# Must be unique in a given SonarQube instance
sonar.host.url=http://localhost:9000/
sonar.projectKey=QuMu-frontend
sonar.token=squ_24b67da80545c00153bcaf9dcdd50d1cefaca94f

# This is the name and version displayed in the SonarQube UI.
sonar.projectName=QuMu-frontend
sonar.projectVersion=1.0.0


# Source directories (REQUERIDO)
sonar.sources=src


# Encoding of the source code
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes

# Pointer to test coverage file 
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
